version: '3'

services:
  app:
    build: https://github.com/tswindell/esp32-arduino-docker.git
    privileged: true
    volumes:
      - ./:/app
      - /dev/bus/usb:/dev/bus/usb
    #command: tail -F /dev/null
    command: make flash
